#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Error: Missing required argument(s)."
  exit 1
fi

read -p "Do you want to generate a new gpg key? (Y/n): " answer
if [ "$answer" == "y" ] || [ "$answer" == "Y" ]; then
  gpg --full-gen-key
  pass init $1
  gpg --with-keygrip -K | grep -A 2 $2 | tail -n 1 | sed -e 's/Keygrip = //g' -e 's/^[[:space:]]*//g' > .pam-gnupg
  gpg-connect-agent --no-autostart reloadagent /bye
fi

echo "Adding new mail-address"
mw -a $1
sed -e "s/mail_address/$1/g" -e "s/real_name/$2/" .config/mutt/.mutt-template > ".config/mutt/accounts/$1.muttrc"
